# Generated by generate_llm_code.py
# LLM: chatgpt
# Mode: original_telemetry

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score


def main() -> None:
    df = pd.read_csv("data/students_graduate_predict.csv", delimiter=";")

    x = df.drop(columns=["Graduated (target)"])
    y = df["Graduated (target)"]

    x_train, x_test, y_train, y_test = train_test_split(
        x, y, test_size=0.15, random_state=1
    )

    model = MLPClassifier(hidden_layer_sizes=[5, 7], max_iter=800)
    model.fit(x_train, y_train)

    _ = model.predict(x.iloc[[0, 1, 2, 3]])

    y_pred_lr = model.predict(x_test)

    accuracy = accuracy_score(y_test, y_pred_lr)
    _ = precision_score(y_test, y_pred_lr)
    _ = recall_score(y_test, y_pred_lr)
    _ = f1_score(y_test, y_pred_lr)

    print(f"ACCURACY={accuracy:.6f}")


if __name__ == "__main__":
    main()