# Generated by generate_llm_code.py
# LLM: claude
# Mode: autonomous

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# --- Robust CSV Loading ---
try:
    df = pd.read_csv("data/wine_dataset.csv")
    if df.shape[1] < 3:
        df = pd.read_csv("data/wine_dataset.csv", sep=";", decimal=",")
except Exception:
    df = pd.read_csv("data/wine_dataset.csv", sep=";", decimal=",")

# --- Column name normalization ---
df.columns = df.columns.str.strip().str.replace(r'\s+', ' ', regex=True)
df = df.loc[:, ~df.columns.str.startswith('Unnamed')]

# --- Identify target and features ---
expected_target = 'quality'
expected_features_num = [
    'fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar',
    'chlorides', 'free_sulfur_dioxide', 'total_sulfur_dioxide', 'density',
    'pH', 'sulphates', 'alcohol'
]
expected_features_cat = ['style']

# Determine actual target
if expected_target in df.columns:
    target_col = expected_target
else:
    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    non_const = [c for c in numeric_cols if df[c].nunique() > 1]
    target_col = non_const[-1] if non_const else numeric_cols[-1]

# Determine actual numeric features
available_num = [c for c in expected_features_num if c in df.columns]
available_cat = [c for c in expected_features_cat if c in df.columns]

# If expected numeric features are missing, fallback to all available numeric except target
if not available_num:
    available_num = [c for c in df.select_dtypes(include=[np.number]).columns if c != target_col]

# If expected cat features missing, pick remaining object columns
if not available_cat:
    available_cat = [c for c in df.select_dtypes(include=['object', 'category']).columns if c != target_col]

feature_cols = available_num + available_cat

# --- Coerce numeric columns ---
for c in available_num + [target_col]:
    df[c] = pd.to_numeric(df[c], errors='coerce')

# Drop rows where target is NaN
df = df.dropna(subset=[target_col])

# Replace inf with NaN then impute numeric features with median
df[available_num] = df[available_num].replace([np.inf, -np.inf], np.nan)
for c in available_num:
    median_val = df[c].median()
    df[c] = df[c].fillna(median_val)

# Fill missing categoricals with mode
for c in available_cat:
    df[c] = df[c].fillna(df[c].mode().iloc[0] if not df[c].mode().empty else 'missing')

assert df.shape[0] > 0, "Dataset empty after preprocessing"

# --- Prepare X, y ---
X = df[list(feature_cols)].copy()
y = df[target_col].copy()

# Determine task type: classification if target has <=30 unique values
n_classes = y.nunique()
is_classification = n_classes >= 2 and n_classes <= 30

if is_classification and n_classes < 2:
    # Trivial baseline
    accuracy = 1.0
    print(f"ACCURACY={accuracy:.6f}")
    import sys
    sys.exit(0)

# --- Train/test split ---
X_train, X_test, y_train, y_test = train_test_split(