# Generated by generate_llm_code.py
# LLM: claude
# Mode: autonomous

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# --- Robust CSV loading ---
try:
    df = pd.read_csv("data/wine_dataset.csv")
    if df.shape[1] < 3:
        df = pd.read_csv("data/wine_dataset.csv", sep=";", decimal=",")
except Exception:
    df = pd.read_csv("data/wine_dataset.csv", sep=";", decimal=",")

# --- Column name normalization ---
df.columns = df.columns.str.strip().str.replace(r"\s+", " ", regex=True)
df = df.loc[:, ~df.columns.str.startswith("Unnamed")]

# --- Schema detection ---
expected_numeric = [
    "fixed_acidity", "volatile_acidity", "citric_acid", "residual_sugar",
    "chlorides", "free_sulfur_dioxide", "total_sulfur_dioxide", "density",
    "pH", "sulphates", "alcohol"
]
expected_target = "quality"
expected_cat = ["style"]

available_cols = list(df.columns)

# Determine target
if expected_target in available_cols:
    target_col = expected_target
else:
    numeric_candidates = df.select_dtypes(include=[np.number]).columns.tolist()
    non_const = [c for c in numeric_candidates if df[c].nunique() > 1]
    target_col = non_const[-1] if non_const else numeric_candidates[0]

# Determine features
feature_cols = [c for c in available_cols if c != target_col]

# --- Coerce numeric columns ---
for c in feature_cols:
    if df[c].dtype == object:
        try:
            converted = pd.to_numeric(df[c], errors="coerce")
            if converted.notna().sum() > 0.5 * len(df):
                df[c] = converted
        except Exception:
            pass

# Coerce target
if df[target_col].dtype == object:
    try:
        converted = pd.to_numeric(df[target_col], errors="coerce")
        if converted.notna().sum() > 0.5 * len(df):
            df[target_col] = converted
    except Exception:
        pass

# --- Separate numeric and categorical features ---
num_features = [c for c in feature_cols if df[c].dtype in [np.float64, np.int64, np.float32, np.int32]]
cat_features = [c for c in feature_cols if df[c].dtype == object]

# --- Handle NaN/inf in numeric columns ---
for c in num_features:
    df[c] = pd.to_numeric(df[c], errors="coerce")
df[num_features] = df[num_features].replace([np.inf, -np.inf], np.nan)

# Drop rows where target is NaN
df = df.dropna(subset=[target_col])

# Impute numeric NaN with median
for c in num_features:
    if df[c].isna().any():
        df[c] = df[c].fillna(df[c].median())

# Impute categorical NaN with mode
for c in cat_features:
    if df[c].isna().any():
        df[c] = df[c].fillna(df[c].mode().iloc[0] if len(df[c].mode()) > 0 else "missing")

assert len(df) > 0, "Dataset is empty after preprocessing"

# --- Determine task type ---
y = df[target_col]
is_classification = True
n_classes = y.nunique()
if n_classes < 2:
    is_classification = False

# --- Prepare X, y ---
X = df[list