# Generated by generate_llm_code.py
# LLM: codex
# Mode: assisted

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

def load_data(path):
    data = pd.read_csv(path, usecols=["Category", "Message"]).fillna("")
    data["Category"] = data["Category"].map({"spam": 0, "ham": 1}).astype("int8")
    return data["Message"], data["Category"]

def train_model(X_train, y_train):
    vectorizer = TfidfVectorizer(stop_words="english")
    X_train_features = vectorizer.fit_transform(X_train)
    model = LogisticRegression()
    model.fit(X_train_features, y_train)
    return model, vectorizer

def evaluate_model(model, vectorizer, X_test, y_test):
    predictions = model.predict(vectorizer.transform(X_test))
    return accuracy_score(y_test, predictions)

def main():
    X, y = load_data("mail_data.csv")
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=3
    )
    model, vectorizer = train_model(X_train, y_train)
    accuracy = evaluate_model(model, vectorizer, X_test, y_test)
    sample_mail = [
        "I've been searching for the right words to thank you for this breather. "
        "I promise i wont take your help for granted and will fulfil my promise. "
        "You have been wonderful and a blessing at all times"
    ]
    _ = model.predict(vectorizer.transform(sample_mail))
    print(f"ACCURACY={accuracy:.6f}")

if __name__ == "__main__":
    main()

# OPTIMIZATION SUMMARY
# - Reduced I/O by loading only required columns and using a single fillna pass.
# - Encoded labels once with int8 to minimize memory footprint.
# - Removed redundant training-accuracy computation and all nonessential prints.
# - Reused the fitted vectorizer to avoid duplicate preprocessing work.
# - Computed test predictions without storing intermediate matrices to save memory.