# Generated by generate_llm_code.py
# LLM: chatgpt
# Mode: assisted

import numpy as np

FILE_NAME = "iris.csv"


def load_iris_csv(file_name: str):
    data = np.genfromtxt(file_name, delimiter=",", skip_header=1, dtype=None, encoding="utf-8")
    features_all = np.column_stack([data["f0"], data["f1"], data["f2"], data["f3"]]).astype(np.float32, copy=False)
    labels_str = data["f4"]

    mapping = {"setosa": 0, "versicolor": 1, "virginica": 2}
    labels = np.fromiter((mapping[s] for s in labels_str), dtype=np.int8, count=labels_str.shape[0])
    return features_all, labels


def compute_centroids(features_2d: np.ndarray, labels: np.ndarray, n_classes: int = 3) -> np.ndarray:
    centroids = np.empty((n_classes, features_2d.shape[1]), dtype=np.float32)
    for k in range(n_classes):
        centroids[k] = features_2d[labels == k].mean(axis=0, dtype=np.float32)
    return centroids


def pairwise_sqeuclidean(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    a2 = np.sum(a * a, axis=1, keepdims=True)
    b2 = np.sum(b * b, axis=1, keepdims=True).T
    return a2 + b2 - 2.0 * (a @ b.T)


def main():
    features_all, labels = load_iris_csv(FILE_NAME)

    features = features_all[:, 2:4].astype(np.float32, copy=False)
    centroids = compute_centroids(features, labels, n_classes=3)

    sq_dists = pairwise_sqeuclidean(features, centroids)
    y_pred = np.argmin(sq_dists, axis=1).astype(np.int8, copy=False)

    accuracy = float(np.mean(y_pred == labels))
    print(f"ACCURACY={accuracy:.6f}")


if __name__ == "__main__":
    main()

# OPTIMIZATION SUMMARY
# - Removed plotting, file outputs, and all non-required prints to cut runtime and I/O energy.
# - Used np.genfromtxt with skip_header and typed parsing to avoid loading an object array then slicing/converting.
# - Converted features to float32 and labels to int8 to reduce memory footprint and improve cache efficiency.
# - Mapped string labels to integers via a single pass (fromiter) to avoid multiple boolean replacement scans.
# - Replaced scipy.cdist with a vectorized squared-Euclidean computation (no sqrt needed for argmin), removing a heavy dependency and saving compute.
# - Kept operations vectorized and avoided unnecessary intermediate arrays/copies with copy=False where safe.
# - Encapsulated logic into small functions for readability and reproducibility without extra overhead.