# Generated by generate_llm_code.py
# LLM: claude
# Mode: assisted

import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

try:
    music_data = pd.read_csv('music.csv')
    if music_data.shape[1] < 2:
        raise ValueError
except (ValueError, pd.errors.ParserError):
    music_data = pd.read_csv('music.csv', sep=';', decimal=',')

X = music_data.drop(columns=['genre'])
y = music_data['genre']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

predictions = model.predict(X_test)
accuracy = accuracy_score(y_test, predictions)

print(f"ACCURACY={accuracy:.6f}")

# Optimization Summary
# - Added fixed random_state=42 for reproducibility in train_test_split and DecisionTreeClassifier.
# - Added robust CSV fallback parsing (try default, then sep=';' with decimal=',').
# - Removed unnecessary prints and kept only the required accuracy output.
# - No redundant intermediate structures or computations; code is minimal and direct.
# - No plots, saved artifacts, or interactive inputs.