# Generated by generate_llm_code.py
# LLM: claude
# Mode: autonomous

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

# --- Robust CSV loading ---
try:
    df = pd.read_csv("data/students_graduate_predict.csv")
    if df.shape[1] < 3:
        raise ValueError("Too few columns, likely wrong separator")
except Exception:
    df = pd.read_csv("data/students_graduate_predict.csv", sep=';', decimal=',')

# If still only 1 column, try sep=';' with default decimal
if df.shape[1] < 3:
    df = pd.read_csv("data/students_graduate_predict.csv", sep=';')

# --- Column name normalization ---
df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace(r'\s+', ' ', regex=True)
df = df[[c for c in df.columns if not c.startswith('Unnamed')]]

# --- Identify target column ---
target_col = None
candidate_targets = ['Graduated (target)', 'Graduated(target)', 'Target', 'target', 'Graduated']
for ct in candidate_targets:
    matches = [c for c in df.columns if c.lower().strip() == ct.lower().strip()]
    if matches:
        target_col = matches[0]
        break

if target_col is None:
    # Fallback: use the last column as target
    target_col = df.columns[-1]

# --- Coerce all columns to numeric where possible ---
for col in df.columns:
    if df[col].dtype == object:
        df[col] = pd.to_numeric(df[col], errors='coerce')

# --- Drop rows where target is NaN ---
df = df.dropna(subset=[target_col])

# --- Separate features and target ---
feature_cols = [c for c in df.columns if c != target_col]
X = df[list(feature_cols)].copy()
y = df[target_col].copy()

# --- Coerce features to numeric, handle NaN/inf ---
for col in X.columns:
    X[col] = pd.to_numeric(X[col], errors='coerce')

X = X.replace([np.inf, -np.inf], np.nan)

# Drop columns that are entirely NaN
nan_cols = X.columns[X.isna().all()]
X = X.drop(columns=nan_cols)

# Impute remaining NaN with column median
for col in X.columns:
    if X[col].isna().any():
        median_val = X[col].median()
        X[col] = X[col].fillna(median_val if not np.isnan(median_val) else 0.0)

# --- Determine task type ---
n_classes = y.nunique()
is_classification = n_classes >= 2 and n_classes <= 50

# --- Ensure dataset is not empty ---
assert X.shape[0] > 0, "Dataset is empty after preprocessing"
assert X.shape[1] > 0, "No feature columns remaining"

# --- Train/test split ---
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y if is_classification else None
)

assert X_train.shape[0] > 0, "Training set is empty"
assert X_test.shape[0] > 0, "Test set is empty"

if is_classification:
    # Check we have at least 2 classes in training
    if y_train.nunique() < 2:
        # Fallback: predict the single class
        accuracy = (y_test == y_train.iloc[0]).mean()
    else:
        # Logistic Regression pipeline - energy efficient, works well on tabular data
        pipeline = Pipeline([
            ('scaler