# Generated by generate_llm_code.py
# LLM: claude
# Mode: autonomous

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Robust CSV loading
try:
    df = pd.read_csv("Iris.csv")
    if df.shape[1] < 2:
        df = pd.read_csv("Iris.csv", sep=";", decimal=",")
except Exception:
    df = pd.read_csv("Iris.csv", sep=";", decimal=",")

# Normalize column names
df.columns = df.columns.str.strip().str.replace(r"\s+", " ", regex=True)
df = df.loc[:, ~df.columns.str.startswith("Unnamed")]

# Drop Id column if present
id_cols = [c for c in df.columns if c.lower() == "id"]
if id_cols:
    df.drop(columns=id_cols, inplace=True)

# Identify target column
target_col = None
for c in df.columns:
    if c.lower() == "species":
        target_col = c
        break

if target_col is None:
    object_cols = df.select_dtypes(include=["object", "category"]).columns.tolist()
    if object_cols:
        target_col = object_cols[-1]
    else:
        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        if len(numeric_cols) >= 2:
            target_col = numeric_cols[-1]
        else:
            target_col = df.columns[-1]

# Encode target if categorical
le = LabelEncoder()
if df[target_col].dtype == object or df[target_col].dtype.name == "category":
    df[target_col] = le.fit_transform(df[target_col].astype(str))
else:
    df[target_col] = pd.to_numeric(df[target_col], errors="coerce")

# Prepare features
feature_cols = [c for c in df.columns if c != target_col]
for c in feature_cols:
    df[c] = pd.to_numeric(df[c], errors="coerce")

# Drop rows with NaN/inf
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(subset=feature_cols + [target_col], inplace=True)

assert df.shape[0] > 0, "Dataset empty after preprocessing"

X = df[list(feature_cols)]
y = df[target_col]

n_classes = y.nunique()
assert n_classes >= 2, "Target has fewer than 2 classes"

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

assert X_train.shape[0] > 0 and X_test.shape[0] > 0

# Lightweight pipeline: StandardScaler + LogisticRegression
pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=200, solver="lbfgs", multi_class="auto", random_state=42))
])

pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"ACCURACY={accuracy:.6f}")

# OPTIMIZATION SUMMARY
# 1. Replaced SVM with LogisticRegression: logistic regression is more energy-efficient
#    and faster on small datasets, while still achieving high accuracy on Iris (~96-100%).
# 2. Used lbfgs solver which is efficient for small multi-class problems.
# 3. Removed matplotlib/seaborn visualization to avoid unnecessary computation and display overhead.
# 4. Removed cross-validation from