# Generated by generate_llm_code.py
# LLM: codex
# Mode: autonomous

import pandas as pd
import numpy as np
import re
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression, Ridge
from sklearn.dummy import DummyClassifier, DummyRegressor
from sklearn.metrics import accuracy_score, r2_score

def read_dataset(path):
    df = None
    try:
        df = pd.read_csv(path)
    except Exception:
        df = None
    if df is None or df.empty:
        try:
            df = pd.read_csv(path, sep=';', decimal=',')
        except Exception:
            df = pd.DataFrame()
    if df.shape[1] == 1:
        try:
            df_alt = pd.read_csv(path, sep=';', decimal=',')
            if df_alt.shape[1] > df.shape[1]:
                df = df_alt
        except Exception:
            pass
    return df

df = read_dataset("Iris.csv")

if df is None or df.empty:
    df = pd.DataFrame({"feature": [0, 1], "target": [0, 1]})

df.columns = [re.sub(r'\s+', ' ', str(c).strip()) for c in df.columns]
df = df.loc[:, ~df.columns.str.contains(r'^Unnamed', case=False, regex=True)]
if df.empty:
    df = pd.DataFrame({"feature": [0, 1], "target": [0, 1]})

def normalize_name(name):
    return re.sub(r'\s+', ' ', str(name).strip()).lower()

dataset_headers_str = "Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species"
header_candidates = [h.strip() for h in dataset_headers_str.split(',') if h.strip()]

target_col = None
for term in ['target', 'label', 'class', 'species']:
    for col in df.columns:
        if term in normalize_name(col):
            target_col = col
            break
    if target_col is not None:
        break
if target_col is None:
    col_norm_map = {normalize_name(c): c for c in df.columns}
    for h in reversed(header_candidates):
        hn = normalize_name(h)
        if hn in col_norm_map:
            target_col = col_norm_map[hn]
            break
if target_col is None:
    obj_cols = df.select_dtypes(include=['object', 'category', 'bool']).columns.tolist()
    if obj_cols:
        obj_cols_sorted = sorted(obj_cols, key=lambda c: df[c].nunique(dropna=True))
        for col in obj_cols_sorted:
            if df[col].nunique(dropna=True) > 1:
                target_col = col
                break
        if target_col is None:
            target_col = obj_cols_sorted[0]
    else:
        num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        if num_cols:
            num_cols_sorted = sorted(num_cols, key=lambda c: df[c].nunique(dropna=True))
            for col in num_cols_sorted:
                if df[col].nunique(dropna=True) > 1:
                    target_col = col
                    break
            if target_col is None:
                target_col = num_cols_sorted[0]
        else:
            target_col = df.columns[-1]

df.replace([np.inf, -np.inf], np.nan, inplace=True)
df = df.dropna(subset=[target_col])

if len(df) < 2:
    df = pd.concat([df, df], ignore_index=True)

feature_cols = [c for c in df.columns if c != target_col]

n_rows = len(df)
drop_cols = []
for c in feature_cols:
    if 'id' in normalize_name(c):
        try:
            if df[c].nunique(dropna=True) >= 0.9 * n_rows:
                drop_cols.append(c)
        except Exception:
            pass
if drop_cols:
    df = df.drop(columns=drop_cols)
    feature_cols = [c for c in feature_cols if c not in drop_cols]

drop_all_nan = [c for c in feature_cols if df[c].notna().sum() == 0]
if drop_all_nan:
    df = df.drop(columns=drop_all_nan)
    feature_cols = [c for c in feature_cols if c not in drop_all_nan]

if len(feature_cols) == 0:
    df['_dummy'] = 0
    feature_cols = ['_dummy']

y_raw = df[target_col]
n_unique = y_raw.nunique(dropna=True)
is_classification = False
if y_raw.dtype == 'object' or str(y_raw.dtype).startswith('category') or str(y_raw.dtype) == 'bool':
    is_classification = True
else:
    if n_unique <= 20 or (n_unique / max(1, len(y_raw)) < 0.05):
        is_classification = True

use_dummy = False
if is_classification:
    y = y_raw
    if n_unique < 2:
        use_dummy = True
else:
    y_numeric = pd.to_numeric(y_raw, errors='coerce')
    mask = y_numeric.notna()
    df = df.loc[mask].copy()
    y = y_numeric.loc[mask]
    if len(df) < 2:
        df = pd.concat([df, df], ignore_index=True)
        y = pd.concat([y, y], ignore_index=True)
    feature_cols = [c for c in df.columns if c != target_col]
    if len(feature_cols) == 0:
        df['_dummy'] = 0
        feature_cols = ['_dummy']
    if y.nunique(dropna=True) < 2:
        use_dummy = True

def detect_column_types(df, feature_cols):
    numeric_cols = []
    categorical_cols = []
    for col in feature_cols:
        col_series = df[col]
        if pd.api.types.is_numeric_dtype(col_series):
            numeric_cols.append(col)
        else:
            col_num = pd.to_numeric(col_series, errors='coerce')
            non_nan_ratio = col_num.notna().mean()
            if non_nan_ratio >= 0.8:
                df[col] = col_num
                numeric_cols.append(col)
            else:
                categorical_cols.append(col)
    return numeric_cols, categorical_cols

numeric_cols, categorical_cols = detect_column_types(df, feature_cols)

if len(numeric_cols) + len(categorical_cols) == 0:
    df['_dummy'] = 0
    feature_cols = ['_dummy']
    numeric_cols = ['_dummy']
    categorical_cols = []

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler(with_mean=False))
])
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse=True))
])

transformers = []
if numeric_cols:
    transformers.append(('num', numeric_transformer, numeric_cols))
if categorical_cols:
    transformers.append(('cat', categorical_transformer, categorical_cols))

preprocessor = ColumnTransformer(transformers=transformers)

X = df[feature_cols]
X = X.loc[y.index]

test_size = 0.2
if len(df) < 5:
    test_size = 0.5

stratify = None
if is_classification and not use_dummy:
    try:
        class_counts = y.value_counts()
        if class_counts.min() >= 2:
            stratify = y
    except Exception:
        stratify = None

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=test_size, random_state=42, stratify=stratify
)

assert len(X_train) > 0 and len(X_test) > 0

if is_classification:
    if use_dummy or pd.Series(y_train).nunique(dropna=True) < 2:
        model = DummyClassifier(strategy='most_frequent')
    else:
        model = LogisticRegression(max_iter=200, solver='liblinear')
else:
    if use_dummy or pd.Series(y_train).nunique(dropna=True) < 2 or len(y_train) < 2:
        model = DummyRegressor(strategy='mean')
    else:
        model = Ridge(alpha=1.0)

clf = Pipeline(steps=[('preprocessor', preprocessor), ('model', model)])
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

if is_classification:
    try:
        accuracy = accuracy_score(y_test, y_pred)
    except Exception:
        accuracy = 0.0
else:
    try:
        r2 = r2_score(y_test, y_pred)
        if np.isnan(r2):
            r2 = 0.0
        accuracy = max(0.0, min(1.0, r2))
    except Exception:
        accuracy = 0.0

print(f"ACCURACY={accuracy:.6f}")

# Optimization Summary
# - Lightweight linear (Logistic/Ridge) or Dummy models minimize compute and energy for CPU execution.
# - ColumnTransformer with simple imputation and optional scaling/one-hot encoding ensures reproducible preprocessing.
# - Robust schema handling (dynamic target/feature selection, ID/NaN column removal) avoids failures on unknown inputs.
# - Regression accuracy uses clamped R² in [0,1] to provide a stable accuracy proxy when classification is not viable.