# Generated by generate_llm_code.py
# LLM: gemini
# Mode: assisted

import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

def load_data(filepath):
    try:
        data = pd.read_csv(filepath)
        if data.shape[1] <= 1:
            raise ValueError
    except (pd.errors.ParserError, ValueError):
        data = pd.read_csv(filepath, sep=';', decimal=',')
    return data

df = load_data("Iris.csv")

if "Id" in df.columns:
    df.drop(columns=["Id"], inplace=True)

target_col = "Species"
X = df.drop(columns=[target_col]).astype("float32")
y = LabelEncoder().fit_transform(df[target_col])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=200, random_state=42))
])

pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

_ = cross_val_score(pipeline, X, y, cv=5)

print(f"ACCURACY={accuracy:.6f}")

# Optimization Summary
# 1. Removed heavy dependencies (matplotlib, seaborn) to reduce memory import overhead and runtime.
# 2. Optimized data loading with use of a robust fallback mechanism for CSV parsing.
# 3. Reduced memory footprint by casting feature data to float32.
# 4. Eliminated redundant computational tasks such as plotting and generating verbose classification reports.
# 5. Improved execution speed by removing unnecessary intermediate print statements and diagnostic loops.
# 6. Ensured reproducibility and stable results by fixing random seeds for both data splitting and model initialization.
# 7. Streamlined preprocessing by combining scaling and modeling into a Pipeline, reducing code complexity and potential data leakage.
# 8. Removed all interactive and side-effecting operations (saving files/plots) to minimize I/O energy consumption.