# Generated by generate_llm_code.py
# LLM: claude
# Mode: assisted

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

df = pd.read_csv("cat_dog_data.csv")
if df.shape[1] == 1:
    df = pd.read_csv("cat_dog_data.csv", sep=";", decimal=",")

label_col = [c for c in df.columns if c.strip().lower() == "label"][0]
X = df.drop(label_col, axis=1).values
y = LabelEncoder().fit_transform(df[label_col])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

model = LinearSVC(dual="auto", max_iter=2000, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"ACCURACY={accuracy:.6f}")

# Optimization Summary
# Replaced SVC(kernel="linear") with LinearSVC which uses liblinear; faster for linear kernels, lower memory.
# Converted DataFrame to numpy array (.values) before fit to avoid repeated pandas overhead.
# Removed classification_report computation since only accuracy is needed.
# Removed redundant encoder variable storage; used inline LabelEncoder.
# Added robust CSV fallback parsing for semicolon-separated files.
# Set random_state on model for reproducibility.
# Removed all prints, plots, and artifact saving per requirements.