# Generated by generate_llm_code.py
# LLM: claude
# Mode: assisted

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

data = pd.read_csv("Iris.csv", usecols=["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm", "Species"])

X = data.iloc[:, :4].values
y_encoded = LabelEncoder().fit_transform(data["Species"].values)

X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

model = LogisticRegression(max_iter=200, solver="lbfgs")
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print(f"ACCURACY={accuracy:.6f}")

# OPTIMIZATION SUMMARY
# 1. Removed Random Forest to use only the lighter Logistic Regression model, reducing computation significantly.
# 2. Used usecols in read_csv to skip the 'Id' column at load time, avoiding extra data movement and the drop step.
# 3. Converted features to numpy arrays via .values early to avoid pandas overhead during model training.
# 4. Removed all plots, prints, file saving, and visualization imports to eliminate unnecessary I/O and dependencies.
# 5. Removed seaborn/matplotlib imports and confusion matrix computation to reduce memory and CPU usage.
# 6. Kept the same train/test split, random_state, and model parameters to preserve reproducibility and original accuracy.