# Generated by generate_llm_code.py
# LLM: gemini
# Mode: autonomous

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

def load_data(path):
    try:
        df = pd.read_csv(path)
        if df.shape[1] <= 1:
            raise ValueError
    except Exception:
        df = pd.read_csv(path, sep=';', decimal=',')
    
    # Normalize column names
    df.columns = [str(c).strip() for c in df.columns]
    df.columns = [" ".join(str(c).split()) for c in df.columns]
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
    return df

def solve():
    dataset_path = 'town_vax_data.csv'
    try:
        df = load_data(dataset_path)
    except Exception:
        # If file is missing or unreadable, exit gracefully as per requirements
        return

    if df.empty:
        return

    # Identify target
    target_col = 'vax_level'
    if target_col not in df.columns:
        # Fallback to the last column if preferred target is missing
        target_col = df.columns[-1]

    # Clean target: drop rows where target is NaN
    df = df.dropna(subset=[target_col])
    
    y = df[target_col]
    X = df.drop(columns=[target_col])

    # Basic feature selection: drop columns with too many unique strings (like 'town')
    # or identify numeric vs categorical
    numeric_features = []
    categorical_features = []

    for col in X.columns:
        # Robust coercion
        if X[col].dtype == 'object':
            # Try converting to numeric
            converted = pd.to_numeric(X[col], errors='coerce')
            if converted.isna().sum() < (0.5 * len(X)):
                X[col] = converted
        
        if np.issubdtype(X[col].dtype, np.number):
            numeric_features.append(col)
        else:
            if X[col].nunique() < 20: # Only use low-cardinality categoricals
                categorical_features.append(col)

    # Ensure we have features
    if not numeric_features and not categorical_features:
        # Use whatever is available if filtering was too strict
        numeric_features = [X.columns[0]]

    # Preprocessing Pipeline
    numeric_transformer = Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())
    ])

    # We use a simple approach for categoricals to save memory/CPU
    # For this specific task, we'll focus on numeric data if available
    preprocessor = ColumnTransformer(
        transformers=[
            ('num', numeric_transformer, numeric_features)
        ],
        remainder='drop'
    )

    # Encode target
    le = LabelEncoder()
    y_encoded = le.fit_transform(y.astype(str))
    
    # Check for trivial case
    if len(np.unique(y_encoded)) < 2:
        print(f"ACCURACY={1.000000:.6f}")
        return

    # Model: Decision Tree (energy efficient, interpretable)
    # Shallow depth to prevent overfitting and minimize compute
    clf = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('classifier', DecisionTreeClassifier(max_depth=5, random_state=42))
    ])

    # Split
    X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

    if len(X_train) == 0 or len(X_test) == 0:
        return

    # Train
    clf.fit(X_train, y_train)

    # Predict
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)

    print(f"ACCURACY={accuracy:.6f}")

if __name__ == "__main__":
    solve()

# Optimization Summary:
# 1. Model Choice: DecisionTreeClassifier was used as it is computationally inexpensive for both training and inference (CPU-friendly).
# 2. Preprocessing: Minimalist approach using StandardScaler and Median Imputation via sklearn Pipeline to avoid data leakage and redundant computations.
# 3. Energy Efficiency: Restricted tree depth (max_depth=5) to limit the number of operations and prevent overfitting, reducing the carbon footprint of the training cycle.
# 4. Robustness: Implemented robust CSV parsing with fallback delimiters and automatic column name normalization to handle schema variations.
# 5. Feature Selection: Automatically identified numeric columns and filtered high-cardinality strings (like town names) to keep the feature space small and memory-efficient.
# 6. Target Handling: Included safety checks for classification targets with fewer than 2 classes and coerced object types to numeric where statistically viable.