# Generated by generate_llm_code.py
# LLM: claude
# Mode: autonomous

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

DATASET_PATH = "data/raw/Train.txt"

# NSL-KDD column names (standard 41 features + label + difficulty)
NSL_KDD_COLUMNS = [
    "duration", "protocol_type", "service", "flag", "src_bytes", "dst_bytes",
    "land", "wrong_fragment", "urgent", "hot", "num_failed_logins", "logged_in",
    "num_compromised", "root_shell", "su_attempted", "num_root",
    "num_file_creations", "num_shells", "num_access_files", "num_outbound_cmds",
    "is_host_login", "is_guest_login", "count", "srv_count", "serror_rate",
    "srv_serror_rate", "rerror_rate", "srv_rerror_rate", "same_srv_rate",
    "diff_srv_rate", "srv_diff_host_rate", "dst_host_count", "dst_host_srv_count",
    "dst_host_same_srv_rate", "dst_host_diff_srv_rate", "dst_host_same_src_port_rate",
    "dst_host_srv_diff_host_rate", "dst_host_serror_rate", "dst_host_srv_serror_rate",
    "dst_host_rerror_rate", "dst_host_srv_rerror_rate", "attack_type", "difficulty"
]

# Robust CSV loading
try:
    df = pd.read_csv(DATASET_PATH, header=None)
except Exception:
    df = pd.read_csv(DATASET_PATH, header=None, sep=';', decimal=',')

# If number of columns matches NSL-KDD schema, assign names
if df.shape[1] == len(NSL_KDD_COLUMNS):
    df.columns = NSL_KDD_COLUMNS
elif df.shape[1] == len(NSL_KDD_COLUMNS) - 1:
    # Some versions lack difficulty column
    df.columns = NSL_KDD_COLUMNS[:-1]
else:
    # Fallback: use generic names
    df.columns = [f"col_{i}" for i in range(df.shape[1])]

# Strip column names
df.columns = [str(c).strip() for c in df.columns]

# Drop unnamed-like columns
df = df[[c for c in df.columns if not c.lower().startswith("unnamed")]]

# Determine target column
if "attack_type" in df.columns:
    target_col = "attack_type"
else:
    # Try last or second-to-last column as target
    candidate = df.columns[-2] if df.shape[1] > 2 else df.columns[-1]
    target_col = candidate

# Binary classification: normal vs attack
df[target_col] = df[target_col].astype(str).str.strip().str.lower()
df["label"] = (df[target_col] != "normal").astype(int)

# Drop difficulty column if present (not a feature)
drop_cols = [target_col]
if "difficulty" in df.columns:
    drop_cols.append("difficulty")

feature_cols = [c for c in df.columns if c not in drop_cols and c != "label"]

# Identify categorical and numeric features
cat_cols = []
num_cols = []
for c in feature_cols:
    if df[c].dtype == object:
        cat_cols.append(c)
    else:
        # Try coercing to numeric
        coerced = pd.to_numeric(df[c], errors='coerce')
        if coerced.notna().sum() / len(df) > 0.5: