# Generated by generate_llm_code.py
# LLM: codex
# Mode: autonomous

import pandas as pd
import numpy as np
import re
import warnings
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression, Ridge
from sklearn.dummy import DummyClassifier, DummyRegressor
from sklearn.metrics import accuracy_score, r2_score

warnings.filterwarnings("ignore")

path = "zoo.csv"
df = None
try:
    df = pd.read_csv(path)
    if df.shape[1] == 1:
        df_alt = pd.read_csv(path, sep=';', decimal=',')
        if df_alt.shape[1] > 1:
            df = df_alt
except Exception:
    df = pd.read_csv(path, sep=';', decimal=',')

def clean_columns(cols):
    cleaned = []
    for c in cols:
        c_str = str(c).strip()
        c_str = re.sub(r'\s+', ' ', c_str)
        cleaned.append(c_str)
    return cleaned

df.columns = clean_columns(df.columns)
df = df.loc[:, ~df.columns.str.contains(r'^Unnamed', case=False, na=False)]
df = df.dropna(axis=1, how='all')
if df.columns.duplicated().any():
    counts = {}
    new_cols = []
    for c in df.columns:
        if c in counts:
            counts[c] += 1
            new_cols.append(f"{c}_{counts[c]}")
        else:
            counts[c] = 0
            new_cols.append(c)
    df.columns = new_cols

assert df.shape[0] > 0 and df.shape[1] > 0

candidate_targets = ['class_type', 'class', 'label', 'target', 'y']
target_col = None
for c in candidate_targets:
    if c in df.columns:
        target_col = c
        break
if target_col is None:
    target_col = df.columns[-1]

def find_alternative_target(dataframe, exclude):
    for col in dataframe.columns:
        if col == exclude:
            continue
        series_num = pd.to_numeric(dataframe[col], errors='coerce')
        if series_num.notna().sum() > 0 and series_num.nunique(dropna=True) > 1:
            return col
    for col in dataframe.columns:
        if col == exclude:
            continue
        if dataframe[col].nunique(dropna=True) > 1:
            return col
    return exclude

if df[target_col].nunique(dropna=True) < 2:
    target_col = find_alternative_target(df, target_col)

y_raw = df[target_col]
y_numeric = pd.to_numeric(y_raw, errors='coerce')
if y_raw.dtype == object or str(y_raw.dtype) == 'category':
    classification = True
    y = y_raw.astype(str)
else:
    if y_numeric.notna().sum() == 0:
        classification = True
        y = y_raw.astype(str)
    else:
        num_unique = y_numeric.nunique(dropna=True)
        classification = num_unique <= max(20, int(0.1 * len(df)))
        y = y_numeric

y = y.replace([np.inf, -np.inf], np.nan)
mask = y.notna()
df = df.loc[mask].copy()
y = y.loc[mask]
assert len(df) > 0

X = df.drop(columns=[target_col])

if classification and y.nunique(dropna=True) < 2:
    classification = False
    if y.dtype == object or str(y.dtype) == 'category':
        y = pd.Series(pd.factorize(y)[0], index=y.index).astype(float)
    else:
        y = pd.to_numeric(y, errors='coerce')

if not classification:
    y = pd.to_numeric(y, errors='coerce')
    y = y.replace([np.inf, -np.inf], np.nan)
    mask = y.notna()
    X = X.loc[mask].copy()
    y = y.loc[mask]
    assert len(y) > 0

if X.shape[1] == 0:
    X = pd.DataFrame({'dummy': np.zeros(len(y))})

numeric_cols = []
categorical_cols = []
for col in X.columns:
    coerced = pd.to_numeric(X[col], errors='coerce')
    if coerced.notna().sum() >= max(1, int(0.5 * len(X))):
        X[col] = coerced
        numeric_cols.append(col)
    else:
        categorical_cols.append(col)

X = X.replace([np.inf, -np.inf], np.nan)

if len(numeric_cols) + len(categorical_cols) == 0:
    X = pd.DataFrame({'dummy': np.zeros(len(y))})
    numeric_cols = ['dummy']
    categorical_cols = []

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler(with_mean=False))
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocess = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_cols),
        ('cat', categorical_transformer, categorical_cols)
    ],
    remainder='drop',
    sparse_threshold=0.3
)

if classification:
    model = LogisticRegression(max_iter=200, solver='liblinear', multi_class='auto', random_state=42)
else:
    model = Ridge(alpha=1.0)

pipeline = Pipeline(steps=[('preprocess', preprocess), ('model', model)])

n_samples = len(X)
test_size = 0.2 if n_samples >= 5 else 0.5
stratify = None
if classification:
    vc = y.value_counts()
    if (vc >= 2).all():
        stratify = y

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=test_size, random_state=42, stratify=stratify
)

assert len(X_train) > 0 and len(X_test) > 0

if classification and pd.Series(y_train).nunique() < 2:
    model = DummyClassifier(strategy='most_frequent')
    pipeline = Pipeline(steps=[('preprocess', preprocess), ('model', model)])

try:
    pipeline.fit(X_train, y_train)
    pred = pipeline.predict(X_test)
except Exception:
    if classification:
        fallback_model = DummyClassifier(strategy='most_frequent')
    else:
        fallback_model = DummyRegressor(strategy='mean')
    pipeline = Pipeline(steps=[('preprocess', preprocess), ('model', fallback_model)])
    pipeline.fit(X_train, y_train)
    pred = pipeline.predict(X_test)

if classification:
    accuracy = accuracy_score(y_test, pred)
else:
    try:
        r2 = r2_score(y_test, pred)
    except Exception:
        r2 = float('nan')
    if not np.isfinite(r2):
        accuracy = 0.0
    else:
        accuracy = max(0.0, min(1.0, r2))

print(f"ACCURACY={accuracy:.6f}")

# Optimization Summary
# - Lightweight linear models (LogisticRegression/Ridge) chosen for CPU efficiency on small tabular data.
# - Simple preprocessing with imputers and one-hot encoding keeps pipeline reproducible and compact.
# - StandardScaler(with_mean=False) stabilizes linear optimization while remaining sparse-friendly.
# - Robust target/feature selection and CSV parsing fallbacks ensure end-to-end execution.
# - Regression fallback reports clipped R² as an accuracy proxy in [0,1].