# Generated by generate_llm_code.py
# LLM: claude
# Mode: autonomous

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

# --- Robust CSV Loading ---
try:
    df = pd.read_csv("spam.csv", encoding="utf-8")
    if df.shape[1] < 2:
        raise ValueError("Too few columns")
except Exception:
    try:
        df = pd.read_csv("spam.csv", sep=";", decimal=",", encoding="utf-8")
    except Exception:
        df = pd.read_csv("spam.csv", encoding="latin-1")

# If reading with default encoding pulled in extra columns (common with this dataset), retry
if df.shape[1] < 2:
    df = pd.read_csv("spam.csv", encoding="latin-1")

# --- Column name normalization ---
df.columns = [str(c).strip().replace("  ", " ") for c in df.columns]
# Drop unnamed columns
df = df[[c for c in df.columns if not c.lower().startswith("unnamed")]]

# --- Identify target and text columns ---
target_col = None
text_col = None

# Try expected names first
for c in df.columns:
    cl = c.lower()
    if cl in ("category", "label", "class", "v1", "target", "spam"):
        target_col = c
    if cl in ("message", "text", "sms", "v2", "email", "content"):
        text_col = c

# Fallback: first column is target, second is text
if target_col is None:
    target_col = df.columns[0]
if text_col is None:
    text_col = df.columns[1] if len(df.columns) > 1 else df.columns[0]

# Keep only the two relevant columns and drop rows with NaN
df = df[[target_col, text_col]].dropna().reset_index(drop=True)

# --- Encode target ---
# Map common spam labels to binary
label_map = {}
unique_labels = df[target_col].astype(str).str.strip().str.lower().unique()

if set(unique_labels).issubset({"ham", "spam"}):
    label_map = {"ham": 0, "spam": 1}
    df["label"] = df[target_col].astype(str).str.strip().str.lower().map(label_map)
else:
    # Generic label encoding
    from sklearn.preprocessing import LabelEncoder
    le = LabelEncoder()
    df["label"] = le.fit_transform(df[target_col].astype(str).str.strip())

df = df.dropna(subset=["label"]).reset_index(drop=True)
df["label"] = df["label"].astype(int)

# Ensure text column is string
df[text_col] = df[text_col].astype(str)

assert df.shape[0] > 0, "Dataset is empty after preprocessing"
assert df["label"].nunique() >= 2, "Target has fewer than 2 classes"

# --- Train/test split ---
X = df[text_col]
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

assert len(X_train) > 0 and len(X_test) > 0, "Train or test set is empty"

# --- Energy-efficient Pipeline: TF-IDF + Multinomial Naive Bayes ---
# Using lightweight stemming via a custom tokenizer to keep it CPU-friendly
import re

def simple_tokenizer(text):
    """Lowercase, remove non-alphanumeric, split into tokens. No heavy NLP libs needed."""
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s