# Generated by generate_llm_code.py
# LLM: gemini
# Mode: original_telemetry

from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn import metrics
import numpy as np
import csv

features = []
labels = []

def make_csv(inpt):
    global features, labels
    first = True
    try:
        with open(inpt, newline='') as csvfile:
            reader = csv.reader(csvfile, delimiter=' ', quotechar='|')
            for row in reader:
                if not row:
                    continue
                cols = row[0].split(",")
                if cols and cols[-1] == '':
                    cols.pop()
                if not first:
                    if not cols:
                        continue
                    both = np.asarray(cols, dtype=np.double).tolist()
                    num = both.pop()
                    if num > 0:
                        num = 1
                    elif num < 0:
                        num = -1
                    labels.append(num)
                    features.append(both)
                else:
                    first = False
    except Exception:
        pass

make_csv('14k.csv')

if features and labels:
    feat_train, feat_test, lab_train, lab_test = train_test_split(
        features, labels, test_size=0.3
    )
    clf = svm.SVC(kernel='linear')
    clf.fit(feat_train, lab_train)
    prediction = clf.predict(feat_test)
    accuracy = metrics.accuracy_score(lab_test, prediction)
    print(f"ACCURACY={accuracy:.6f}")

# OPTIMIZATION SUMMARY
# - Refactored the code into a baseline execution script that performs training and evaluation.
# - Removed original comments, interactive input methods (predict/takeInput), and original print statements.
# - Removed model persistence (pickle saving/loading) and unit testing framework.
# - Fixed potential IndexError in CSV parsing by checking for empty rows and columns.
# - Maintained the original SVC linear kernel, 70/30 train-test split, and label binarization logic.
# - Implemented the required accuracy output format.