# Generated by generate_llm_code.py
# LLM: claude
# Mode: assisted

import pickle
import numpy as np
from sklearn.metrics import accuracy_score

RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

with open("dict.pickle", "rb") as f:
    clf = pickle.load(f)

from sklearn.model_selection import train_test_split

has_training_data = hasattr(clf, 'support_vectors_')

if has_training_data:
    try:
        import pandas as pd
        try:
            df = pd.read_csv('14k.csv')
            if df.shape[1] < 2:
                df = pd.read_csv('14k.csv', sep=';', decimal=',')
        except Exception:
            df = pd.read_csv('14k.csv', sep=';', decimal=',')

        data = df.values.astype(np.float64)
        last_col = data[:, -1] if data.shape[1] > 0 else None

        mask_trailing = np.isnan(data[:, -1]) if data.shape[1] > 0 else np.zeros(len(data), dtype=bool)
        if np.all(mask_trailing):
            data = data[:, :-1]
            last_col = data[:, -1]
            feature_data = data[:, :-1]
        else:
            feature_data = data[:, :-1]

        raw_labels = last_col.copy()
        labels = np.where(raw_labels > 0, 1.0, np.where(raw_labels < 0, -1.0, 0.0))

        feat_train, feat_test, lab_train, lab_test = train_test_split(
            feature_data, labels, test_size=0.3, random_state=RANDOM_SEED)

        clf.fit(feat_train, lab_train)
        prediction = clf.predict(feat_test)
        accuracy = accuracy_score(lab_test, prediction)
    except Exception:
        try:
            import csv
            features = []
            labels_list = []
            first = True
            with open('14k.csv', newline='') as csvfile:
                reader = csv.reader(csvfile, delimiter=' ', quotechar='|')
                for row in reader:
                    cols = row[0].split(",")
                    if cols[-1] == '':
                        cols.pop()
                    if not first:
                        both = np.asarray(cols, dtype=np.float64).tolist()
                        num = both.pop()
                        if num > 0:
                            num = 1
                        elif num < 0:
                            num = -1
                        labels_list.append(num)
                        features.append(both)
                    else:
                        first = False

            features = np.array(features, dtype=np.float64)
            labels_arr = np.array(labels_list, dtype=np.float64)

            feat_train, feat_test, lab_train, lab_test = train_test_split(
                features, labels_arr, test_size=0.3, random_state=RANDOM_SEED)

            clf.fit(feat_train, lab_train)
            prediction = clf.predict(feat_test)
            accuracy = accuracy_score(lab_test, prediction)
        except Exception:
            accuracy = 0.0
else:
    accuracy = 0.0

print(f"ACCURACY={accuracy:.6f}")

# Optimization Summary
# - Removed all plots, visualizations, interactive inputs, and print/logging statements.
# - Removed file saving (saveModel) to avoid unnecessary side effects.
# - Removed unittest class as it is not part of the core ML pipeline.
# - Removed redundant global mutable lists (features, labels, pFeatures) in favor of numpy arrays.
# - Used numpy array operations instead of Python-level loops where possible to reduce overhead.
# - Added fixed random seed for reproducibility in train_test_split.
# - Implemented robust CSV parsing with pandas fallback to semicolon/comma decimal format.
#