# Generated by generate_llm_code.py
# LLM: claude
# Mode: autonomous

import pandas as pd
import numpy as np
import os
import glob
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Discover the dataset: look for CSV files in the project directory
project_dir = os.path.dirname(os.path.abspath(__file__))
csv_files = glob.glob(os.path.join(project_dir, "**", "*.csv"), recursive=True)

# If no CSV found in project dir, also check common locations
if not csv_files:
    for candidate in [
        os.path.join(project_dir, "iris.csv"),
        os.path.join(project_dir, "data", "iris.csv"),
        os.path.join(project_dir, "Iris.csv"),
        os.path.join(project_dir, "data", "Iris.csv"),
        "iris.csv",
        "Iris.csv",
    ]:
        if os.path.exists(candidate):
            csv_files = [candidate]
            break

# If still no CSV, try to load from sklearn datasets as fallback
if not csv_files:
    try:
        from sklearn.datasets import load_iris
        iris = load_iris()
        df = pd.DataFrame(iris.data, columns=iris.feature_names)
        df["target"] = iris.target
        target_col = "target"
    except Exception:
        raise FileNotFoundError("No CSV dataset found and sklearn iris fallback failed.")
else:
    dataset_path = csv_files[0]

    # Robust CSV parsing
    try:
        df = pd.read_csv(dataset_path)
        if df.shape[1] <= 1:
            df = pd.read_csv(dataset_path, sep=";", decimal=",")
    except Exception:
        df = pd.read_csv(dataset_path, sep=";", decimal=",")

    # Clean column names
    df.columns = df.columns.str.strip()
    df.columns = [" ".join(c.split()) for c in df.columns]
    # Drop unnamed columns
    df = df[[c for c in df.columns if not c.lower().startswith("unnamed")]]

    # Drop Id-like columns (common in Iris datasets)
    id_cols = [c for c in df.columns if c.lower() in ("id",)]
    df = df.drop(columns=id_cols, errors="ignore")

    # Identify target column: prefer columns with "species", "class", "variety", "target", "label"
    target_col = None
    target_keywords = ["species", "class", "variety", "target", "label"]
    for col in df.columns:
        if any(kw in col.lower() for kw in target_keywords):
            target_col = col
            break

    # If no keyword match, use the last column if it's non-numeric or has few unique values
    if target_col is None:
        last_col = df.columns[-1]
        if df[last_col].dtype == object or df[last_col].nunique() <= 20:
            target_col = last_col
        else:
            # Pick the first object column
            obj_cols = df.select_dtypes(include=["object"]).columns.tolist()
            if obj_cols:
                target_col = obj_cols[0]
            else:
                target_col = df.columns[-1]

# Separate features and target
feature_cols = [c for c in df.columns if c != target_col]

# Coerce numeric features
for c in feature_cols:
    df[c] = pd.to_numeric(df[c], errors="coerce")

# Drop non-numeric feature columns that couldn't be converted
numeric_feature_cols = [c for c in feature_cols if df[c].dtype in [np.float64, np.float32, np.int64, np.int32, float, int]]
feature_cols = numeric_feature_cols

#

raise SyntaxError("Did not finish generating code")