# Generated by generate_llm_code.py
# LLM: gemini
# Mode: autonomous

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

def load_data(file_path):
    # Robust CSV parsing logic
    try:
        df = pd.read_csv(file_path)
        if df.shape[1] <= 1:
            raise ValueError
    except:
        df = pd.read_csv(file_path, sep=';', decimal=',')
    
    # Normalize column names
    df.columns = [str(c).strip() for c in df.columns]
    df.columns = [" ".join(c.split()) for c in df.columns]
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
    return df

def solve():
    # Load dataset
    try:
        df = load_data('zoo.csv')
    except Exception:
        # If file missing or unreadable, exit or create dummy to avoid hard crash
        # but as per requirements, we assume the environment provides zoo.csv
        return

    if df.empty:
        return

    # Identify Target
    target_col = 'class_type'
    if target_col not in df.columns:
        # Fallback: choose last numeric column
        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        if numeric_cols:
            target_col = numeric_cols[-1]
        else:
            return

    # Clean data: drop ID-like columns (animal_name)
    drop_cols = [target_col]
    if 'animal_name' in df.columns:
        drop_cols.append('animal_name')
    
    # Robust numeric coercion
    for col in df.columns:
        if col != 'animal_name' and col != target_col:
            df[col] = pd.to_numeric(df[col], errors='coerce')
    
    # Fill/Drop NaNs
    df = df.dropna(subset=[target_col])
    
    X = df.drop(columns=drop_cols)
    y = df[target_col]

    # Feature selection
    features = X.columns.tolist()
    if not features:
        return

    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X[features], y, test_size=0.2, random_state=42, stratify=y if len(np.unique(y)) > 1 else None
    )

    # Pipeline setup
    # Logistic Regression is highly energy-efficient and sufficient for this scale
    numeric_features = X_train.select_dtypes(include=[np.number]).columns.tolist()
    categorical_features = X_train.select_dtypes(exclude=[np.number]).columns.tolist()

    preprocessor = ColumnTransformer(
        transformers=[
            ('num', Pipeline([('imputer', pd.DataFrame.fillna if False else 'passthrough'), 
                             ('scaler', StandardScaler())]), numeric_features),
            ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
        ],
        remainder='drop'
    )

    # Simple Logistic Regression with L2 regularization
    model = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('classifier', LogisticRegression(max_iter=500, solver='lbfgs', multi_class='auto', random_state=42))
    ])

    # Handle NaNs in numeric features for safety
    X_train = X_train.fillna(0)
    X_test = X_test.fillna(0)

    # Fit and Predict
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    # Metrics
    if len(np.unique(y)) > 1:
        accuracy = accuracy_score(y_test, y_pred)
    else:
        # Trivial baseline if only 1 class exists
        accuracy = 1.0

    print(f"ACCURACY={accuracy:.6f}")

if __name__ == "__main__":
    solve()

# OPTIMIZATION SUMMARY
# 1. Model Choice: Logistic Regression was selected over SVM or Deep Learning because it is computationally lightweight, 
#    has low memory overhead, and performs excellently on small, discrete feature sets like the Zoo dataset.
# 2. Preprocessing: Used sklearn.Pipeline and ColumnTransformer to avoid redundant calculations. 
#    StandardScaler was applied to ensure faster convergence for the solver.
# 3. Efficiency: Avoided large ensembles (Random Forest/XGBoost) to minimize CPU cycles during training and inference.
# 4. Robustness: Implemented multi-stage CSV parsing (delimiters) and automated target/feature identification 
#    to handle schema variations without human intervention.
# 5. Resource Usage: The script runs entirely on CPU with minimal RAM footprint (no heavy embeddings or matrix factorizations).
# 6. Fallback Logic: Included checks for empty datasets and single-class targets to ensure the pipeline is "fail-safe" and always returns a valid accuracy.