# Generated by generate_llm_code.py
# LLM: chatgpt
# Mode: assisted

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

def load_data(path: str):
    df = pd.read_csv(path)
    X = df.iloc[:, 1:17].to_numpy(dtype=np.float32, copy=False)
    y = df.iloc[:, 17].to_numpy(copy=False)
    return X, y

def train_and_evaluate(X, y, test_size=0.25, random_state=0):
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=random_state
    )
    clf = SVC()
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    return accuracy

def main():
    X, y = load_data("zoo.csv")
    accuracy = train_and_evaluate(X, y)
    print(f"ACCURACY={accuracy:.6f}")

if __name__ == "__main__":
    main()

# Optimizations applied:
# 1) Removed unused imports (seaborn, matplotlib, numpy extras) to reduce load time and memory footprint.
# 2) Eliminated redundant computations: removed unused head(), intermediate score(), slice prediction, and confusion-matrix-based manual accuracy.
# 3) Used accuracy_score directly to avoid building a confusion matrix (less computation and memory).
# 4) Converted features to float32 with zero-copy when possible to reduce memory bandwidth and improve cache efficiency.
# 5) Wrapped logic into small functions to keep code modular and avoid accidental repeated work.