# Generated by generate_llm_code.py
# LLM: gemini
# Mode: autonomous

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

"""
Justification:
A Decision Tree Classifier was selected for this task to ensure maximum energy efficiency. 
Decision trees have O(n_samples * n_features * log(n_samples)) complexity, making them 
computationally lightweight for training and inference on small datasets like the Zoo dataset. 
This approach avoids the significant energy consumption associated with iterative 
gradient-based solvers (e.g., Neural Networks, SVMs) and does not require feature 
scaling or complex embeddings, further reducing the carbon footprint of the pipeline.
"""

def run_pipeline(file_path):
    df = pd.read_csv(file_path)
    
    X = df.drop(columns=['animal_name', 'class_type'])
    y = df['class_type']
    
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    
    model = DecisionTreeClassifier(
        criterion='gini',
        max_depth=None,
        min_samples_split=2,
        random_state=42
    )
    
    model.fit(X_train, y_train)
    
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    
    print(f"ACCURACY={accuracy:.6f}")

if __name__ == "__main__":
    run_pipeline('zoo.csv')