# Generated by generate_llm_code.py
# LLM: gemini
# Mode: autonomous

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Data Loading
# Assuming the dataset is named 'dataset.csv' based on provided headers
try:
    df = pd.read_csv('dataset.csv')
except FileNotFoundError:
    # Creating a dummy structure if file not found for script integrity
    df = pd.DataFrame(columns=['sender', 'subject', 'body', 'urls', 'filename', 'label', 'text'])

# Preprocessing Pipeline
# Using 'text' column as primary feature, falling back to concatenated fields if 'text' is empty
df['processed_text'] = df['text'].fillna('')
mask = df['processed_text'] == ''
df.loc[mask, 'processed_text'] = df.loc[mask, 'subject'].fillna('') + " " + df.loc[mask, 'body'].fillna('')

# Feature and Label Selection
X = df['processed_text']
y = df['label']

# Reproducible Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y if len(np.unique(y)) > 1 else None)

# Energy-efficient Vectorization
# TF-IDF is significantly less compute-intensive than deep learning embeddings
# max_features is limited to 3000 to reduce memory footprint and training time
vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=3000,
    ngram_range=(1, 2),
    sublinear_tf=True
)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# Lightweight Model Choice
# Logistic Regression provides a convex optimization problem with fast convergence on CPU
# 'liblinear' solver is efficient for smaller datasets
clf = LogisticRegression(
    solver='liblinear',
    C=1.0,
    random_state=42,
    max_iter=500
)

# Training
clf.fit(X_train_vec, y_train)

# Evaluation
y_pred = clf.predict(X_test_vec)
accuracy = accuracy_score(y_test, y_pred)

print(f"ACCURACY={accuracy:.6f}")

# OPTIMIZATION SUMMARY
# 1. Feature Engineering: Utilized TF-IDF vectorization which is computationally inexpensive compared to BERT/Transformers.
# 2. Vocabulary Limitation: Capped TF-IDF features at 3000 to minimize RAM usage and carbon footprint during matrix operations.
# 3. Model Selection: Logistic Regression was chosen for its low algorithmic complexity (O(n_features * n_samples)) and high CPU efficiency.
# 4. Hardware Awareness: Designed to run on standard CPU without requiring GPU acceleration, reducing energy consumption.
# 5. Convergence: Used 'liblinear' solver which is optimized for small-to-medium scale classification tasks with rapid convergence.
# 6. Preprocessing: Implemented a vectorized pandas approach for text merging to minimize iterative CPU cycles.