# Generated by generate_llm_code.py
# LLM: chatgpt
# Mode: original_telemetry

from sklearn.model_selection import train_test_split
from sklearn import metrics
import pickle
import numpy as np
import csv
import unittest
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=4)
features = []
labels = []
pFeatures = []


def makeCSV(inpt):
    try:
        first = True
        with open(inpt, newline="") as csvfile:
            reader = csv.reader(csvfile, delimiter=" ", quotechar="|")
            for row in reader:
                cols = row[0].split(",")
                if cols[len(cols) - 1] == "":
                    cols.pop()
                if first is False:
                    both = np.asarray(cols, dtype=np.double).tolist()
                    num = both.pop()
                    if num > 0:
                        num = 1
                    elif num < 0:
                        num = -1
                    labels.append(num)
                    features.append(both)
                else:
                    first = False
    except:
        pass


def trainAndTestModel():
    makeCSV("14k.csv")
    feat_train, feat_test, lab_train, lab_test = train_test_split(
        features, labels, test_size=0.3
    )
    classifier.fit(feat_train, lab_train)
    y_pred = classifier.predict(feat_test)
    accuracy = metrics.accuracy_score(lab_test, y_pred)
    print(f"ACCURACY={accuracy:.6f}")


def loadModel():
    global classifier
    pickle_in = open("dict.pickle", "rb")
    classifier = pickle.load(pickle_in)


def saveModel():
    global classifier
    pickle_out = open("dict.pickle", "wb")
    pickle.dump(classifier, pickle_out)
    pickle_out.close()


def wipeVariables():
    global features
    global labels
    features = []
    labels = []


def predict():
    loadModel()
    takeInput()
    classifier.predict(pFeatures)
    saveModel()


def takeInput():
    try:
        first = True
        with open("input.csv", newline="") as csvfile:
            reader = csv.reader(csvfile, delimiter=" ", quotechar="|")
            for row in reader:
                cols = row[0].split(",")
                if cols[len(cols) - 1] == "":
                    cols.pop()
                if first is False:
                    ftrs = np.asarray(cols, dtype=np.double).tolist()
                    pFeatures.append(ftrs)
                else:
                    first = False
    except:
        pass


predict()


class Testing(unittest.TestCase):
    def setUp(self):
        wipeVariables()
        return super().setUp()

    def tearDown(self):
        wipeVariables()
        return super().tearDown()

    def test_MakeCSV4(self):
        makeCSV("test.csv")
        self.assertEqual(len(features), 4)

    def test_MakeCSV2(self):
        makeCSV("test2.csv")
        self.assertEqual(len(labels), 2)