# Generated by generate_llm_code.py
# LLM: chatgpt
# Mode: original_telemetry

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import pylab
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report
import tensorflow as tf
from tensorflow.keras.models import Sequential
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier


def main() -> None:
    df = pd.read_csv("heart/heart_dataset_.csv")

    y = df.target.values
    x_data = df.drop(["target"], axis=1)
    x = (x_data - x_data.min()) / (x_data.max() - x_data.min())

    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

    x_train = x_train.T
    y_train = y_train.T
    x_test = x_test.T
    y_test = y_test.T

    lr = LogisticRegression(solver="lbfgs")
    lr.fit(x_train.T, y_train.T)

    knn = KNeighborsClassifier(n_neighbors=2)
    knn.fit(x_train.T, y_train.T)
    _prediction = knn.predict(x_test.T)

    scoreList = []
    for i in range(1, 20):
        knn2 = KNeighborsClassifier(n_neighbors=i)
        knn2.fit(x_train.T, y_train.T)
        scoreList.append(knn2.score(x_test.T, y_test.T))

    svm = SVC(random_state=1)
    svm.fit(x_train.T, y_train.T)

    nb = GaussianNB()
    nb.fit(x_train.T, y_train.T)

    dtc = DecisionTreeClassifier()
    dtc.fit(x_train.T, y_train.T)

    rf = RandomForestClassifier(n_estimators=1000, random_state=1)
    rf.fit(x_train.T, y_train.T)

    y_head_lr = lr.predict(x_test.T)
    knn3 = KNeighborsClassifier(n_neighbors=3)
    knn3.fit(x_train.T, y_train.T)
    y_head_knn = knn3.predict(x_test.T)
    y_head_svm = svm.predict(x_test.T)
    y_head_nb = nb.predict(x_test.T)
    y_head_dtc = dtc.predict(x_test.T)
    y_head_rf = rf.predict(x_test.T)

    _cm_lr = confusion_matrix(y_test, y_head_lr)
    _cm_knn = confusion_matrix(y_test, y_head_knn)
    _cm_svm = confusion_matrix(y_test, y_head_svm)
    _cm_nb = confusion_matrix(y_test, y_head_nb)
    _cm_dtc = confusion_matrix(y_test, y_head_dtc)
    _cm_rf = confusion_matrix(y_test, y_head_rf)

    accuracy = lr.score(x_test.T, y_test.T)
    print(f"ACCURACY={accuracy:.6f}")


if __name__ == "__main__":
    main()