# Generated by generate_llm_code.py
# LLM: claude
# Mode: autonomous

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
import warnings
warnings.filterwarnings("ignore")

DATASET_PATH = "bodyPerformance.csv"

# Robust CSV loading
df = None
try:
    df = pd.read_csv(DATASET_PATH)
    if df.shape[1] < 3:
        df = pd.read_csv(DATASET_PATH, sep=';', decimal=',')
except Exception:
    try:
        df = pd.read_csv(DATASET_PATH, sep=';', decimal=',')
    except Exception as e:
        raise RuntimeError(f"Cannot read CSV: {e}")

# Normalize column names
df.columns = df.columns.str.strip().str.replace(r'\s+', ' ', regex=True)
df = df[[c for c in df.columns if not c.startswith('Unnamed')]]

# Identify target column - look for likely classification target
# Based on headers, "Blass" (likely "class") is the target
target_col = None
candidate_targets = ['Blass', 'class', 'Class', 'blass', 'grade', 'Grade', 'label', 'Label']
for ct in candidate_targets:
    matches = [c for c in df.columns if c.strip().lower() == ct.strip().lower()]
    if matches:
        target_col = matches[0]
        break

# If no known target found, pick the last column if it's non-numeric or has few unique values
if target_col is None:
    last_col = df.columns[-1]
    if df[last_col].dtype == object or df[last_col].nunique() <= 20:
        target_col = last_col
    else:
        # Pick first object column
        obj_cols = df.select_dtypes(include='object').columns.tolist()
        if obj_cols:
            target_col = obj_cols[0]
        else:
            target_col = last_col

# Drop rows where target is NaN
df = df.dropna(subset=[target_col])

# Determine if classification or regression
is_classification = df[target_col].dtype == object or df[target_col].nunique() <= 20

# Separate features and target
feature_cols = [c for c in df.columns if c != target_col]

# Identify numeric and categorical feature columns
numeric_features = []
categorical_features = []

for c in feature_cols:
    col_data = pd.to_numeric(df[c], errors='coerce')
    non_null_ratio = col_data.notna().mean()
    if non_null_ratio > 0.5:
        numeric_features.append(c)
        df[c] = col_data
    else:
        categorical_features.append(c)

# Coerce numeric columns, handle inf
for c in numeric_features:
    df[c] = pd.to_numeric(df[c], errors='coerce')
    df[c] = df[c].replace([np.inf, -np.inf], np.nan)

# Fill numeric NaNs with median
for c in numeric_features:
    median_val = df[c].median()
    df[c] = df[c].fillna(median_val)

# Fill categorical NaNs with mode
for c in categorical_features:
    df[c] = df[c].astype(str)
    mode_val = df[c].mode()
    if len(mode_val) > 0:
        df[c] = df[c].fillna(mode_val.iloc[0])
    else:
        df[c] = df[c].fillna('unknown')

# Encode target
if is_classification:
    le = LabelEncoder()
    y = le.fit_transform(df[target_col